'use client';
import '../styles/globals.scss';
import cn from 'classnames'
import { Playfair_Display, Open_Sans, Montserrat } from 'next/font/google'
import { useEffect, useState } from 'react';
import { LoginCandidate } from '@/components/mainPages/Register/LoginCandidate';

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfire',
  weight: ['400', '500', '600', '700']
})

const opensans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-opensans',
  weight: ['400', '500', '600', '700']
})

const monserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-monserrat',
  weight: ['100', '300','400', '500', '600', '700', '800', '900']
})

// Metadata will be set later
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [auth, setAuth] = useState<boolean>(false);

  useEffect(() => {
    const res = localStorage.getItem('token')

    if (res) {
      setAuth(true);
    }
  }, []);

  return (
    <html
      lang="en"
      className={cn(
        [playfair.variable],
        [opensans.variable],
        [monserrat.variable]
      )}
    >
      <body>

        {/* {auth ? (
          <main className="rootlayout__main">
            {children}
          </main>
        ) : (
          <LoginCandidate />
        )} */}

          <main>
            {children}
          </main>
      </body>
    </html>
  )
}
